services:
  app:
    build: .
    container_name: planora-app
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://mysql:3306/planora
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - planora-net

  mysql:
    image: mysql:8.0
    container_name: planora-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: planora
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - planora-net

volumes:
  mysql_data:

networks:
  planora-net: